//! Lowers a Kittine [`Program`] into idiomatic Leptos 0.7 Rust source.
//!
//! The mapping this module implements is exactly the one from the language
//! spec:
//!
//! - `<{x}> >> y` the *first* time `x` is seen in a component becomes a
//!   signal declaration: `let (x, set_x) = signal(y);`
//! - `<{x}> >> expr` any *later* time becomes a mutation:
//!   `set_x.update(|n| ..);`, with the `x + 1` / `x - 1` / `x * 1` / `x / 1`
//!   shape special-cased to the idiomatic `*n += 1;` form.
//! - `craft<expr>` becomes `leptos::logging::log!(..)`.
//! - `if>` / `orif>` / `else>` become `if` / `else if` / `else`, with `>>`
//!   conditions becoming `==` comparisons and variable reads becoming
//!   `.get()` calls.
//! - The `return ( .. )` JSX tree becomes a Leptos `view! { .. }` block,
//!   with `onX` attributes rewritten to Leptos's `on:x=` event bindings.

use crate::ast::*;
use std::collections::HashSet;

const INDENT: &str = "    ";

pub fn generate(program: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by kittine-compiler. Do not edit by hand.\n");
    out.push_str("#![allow(unused_braces, unused_variables)]\n\n");
    out.push_str("use leptos::prelude::*;\n\n");
    for component in &program.components {
        out.push_str(&gen_component(component));
        out.push('\n');
    }
    out
}

fn push_line(out: &mut String, indent: usize, text: &str) {
    for line in text.lines() {
        out.push_str(&INDENT.repeat(indent));
        out.push_str(line);
        out.push('\n');
    }
}

fn gen_component(component: &Component) -> String {
    let mut out = String::new();
    out.push_str("#[component]\n");
    out.push_str(&format!(
        "pub fn {}() -> impl IntoView {{\n",
        component.name
    ));

    let mut declared: HashSet<String> = HashSet::new();
    for stmt in &component.body {
        gen_stmt(stmt, &mut declared, &mut out, 1);
    }

    match &component.return_view {
        Some(view) => {
            push_line(&mut out, 1, "view! {");
            out.push_str(&jsx_to_rust(view, &declared, 2));
            push_line(&mut out, 1, "}");
        }
        None => push_line(&mut out, 1, "view! { <></> }"),
    }

    out.push_str("}\n");
    out
}

// ---- statements ----------------------------------------------------------

fn gen_stmt(stmt: &Stmt, declared: &mut HashSet<String>, out: &mut String, indent: usize) {
    match stmt {
        Stmt::VarAssign { name, value } => {
            if declared.contains(name) {
                let body = mutation_body(name, value, declared);
                push_line(out, indent, &format!("set_{name}.update(|n| {body});"));
            } else {
                let value_code = expr_to_rust(value, declared);
                push_line(
                    out,
                    indent,
                    &format!("let ({name}, set_{name}) = signal({value_code});"),
                );
                declared.insert(name.clone());
            }
        }
        Stmt::Craft { value } => {
            let code = match value {
                Expr::Str(s) => format!("leptos::logging::log!(\"{}\");", escape_str(s)),
                other => format!(
                    "leptos::logging::log!(\"{{}}\", {});",
                    expr_to_rust(other, declared)
                ),
            };
            push_line(out, indent, &code);
        }
        Stmt::If {
            branches,
            else_body,
        } => {
            for (i, (cond, body)) in branches.iter().enumerate() {
                let cond_code = render_condition(cond, declared);
                if i == 0 {
                    push_line(out, indent, &format!("if {cond_code} {{"));
                } else {
                    push_line(out, indent, &format!("}} else if {cond_code} {{"));
                }
                for s in body {
                    gen_stmt(s, declared, out, indent + 1);
                }
            }
            if let Some(body) = else_body {
                push_line(out, indent, "} else {");
                for s in body {
                    gen_stmt(s, declared, out, indent + 1);
                }
            }
            push_line(out, indent, "}");
        }
        Stmt::Expr(expr) => {
            push_line(out, indent, &format!("{};", expr_to_rust(expr, declared)));
        }
    }
}

/// Body of `set_name.update(|n| BODY)` for a mutation of `name`, as a bare
/// expression with no trailing `;` — callers decide whether the surrounding
/// context needs one.
fn mutation_body(name: &str, value: &Expr, declared: &HashSet<String>) -> String {
    if let Expr::Binary { left, op, right } = value
        && is_same_var(left, name)
        && let Expr::Number(n) = **right
    {
        let compound_op = match op {
            BinOp::Add => Some("+="),
            BinOp::Sub => Some("-="),
            BinOp::Mul => Some("*="),
            BinOp::Div => Some("/="),
            _ => None,
        };
        if let Some(op_str) = compound_op {
            return format!("*n {op_str} {}", fmt_num(n));
        }
    }
    format!("*n = {}", substitute_self(value, name, declared))
}

fn is_same_var(expr: &Expr, name: &str) -> bool {
    matches!(expr, Expr::Ident(n) | Expr::VarRead(n) if n == name)
}

/// Renders `value` as a Rust expression for use inside `|n| ..`, rewriting
/// self-references (`x` inside the update for `x`) to `*n` instead of
/// `x.get()`.
fn substitute_self(expr: &Expr, name: &str, declared: &HashSet<String>) -> String {
    match expr {
        Expr::Ident(n) | Expr::VarRead(n) if n == name => "*n".to_string(),
        Expr::Ident(n) | Expr::VarRead(n) => render_var_read(n, declared),
        Expr::Number(n) => fmt_num(*n),
        Expr::Str(s) => format!("\"{}\"", escape_str(s)),
        Expr::Binary { left, op, right } => format!(
            "({} {} {})",
            substitute_self(left, name, declared),
            op_str(*op),
            substitute_self(right, name, declared)
        ),
        Expr::InlineAssign { name: n, value } => mutation_expr(n, value, declared),
    }
}

/// The mutation as a bare expression (no trailing `;`), for use as a JSX
/// event-handler closure body: `move |_| set_x.update(|n| ..)`.
fn mutation_expr(name: &str, value: &Expr, declared: &HashSet<String>) -> String {
    let body = mutation_body(name, value, declared);
    format!("set_{name}.update(|n| {body})")
}

// ---- expressions -----------------------------------------------------------

fn render_var_read(name: &str, declared: &HashSet<String>) -> String {
    if declared.contains(name) {
        format!("{name}.get()")
    } else {
        name.to_string()
    }
}

fn expr_to_rust(expr: &Expr, declared: &HashSet<String>) -> String {
    match expr {
        Expr::Ident(name) | Expr::VarRead(name) => render_var_read(name, declared),
        Expr::Number(n) => fmt_num(*n),
        Expr::Str(s) => format!("\"{}\"", escape_str(s)),
        Expr::Binary { left, op, right } => format!(
            "({} {} {})",
            expr_to_rust(left, declared),
            op_str(*op),
            expr_to_rust(right, declared)
        ),
        Expr::InlineAssign { name, value } => mutation_expr(name, value, declared),
    }
}

/// Renders a top-level `if>` condition without the redundant outer
/// parentheses `expr_to_rust` would otherwise add around every `Binary`.
fn render_condition(expr: &Expr, declared: &HashSet<String>) -> String {
    match expr {
        Expr::Binary { left, op, right } => format!(
            "{} {} {}",
            expr_to_rust(left, declared),
            op_str(*op),
            expr_to_rust(right, declared)
        ),
        other => expr_to_rust(other, declared),
    }
}

fn op_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Eq => "==",
    }
}

fn fmt_num(n: f64) -> String {
    if n.fract() == 0.0 && n.abs() < 1e15 {
        format!("{}", n as i64)
    } else {
        format!("{n}")
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

// ---- JSX --------------------------------------------------------------------

fn jsx_attr_leptos_name(name: &str) -> (String, bool) {
    let bytes = name.as_bytes();
    if name.len() > 2 && &name[0..2] == "on" && bytes[2].is_ascii_uppercase() {
        let event = name[2..].to_lowercase();
        (format!("on:{event}"), true)
    } else {
        (name.to_string(), false)
    }
}

fn jsx_attr_value(value: &JsxAttrValue, is_event: bool, declared: &HashSet<String>) -> String {
    match value {
        JsxAttrValue::Str(s) => format!("\"{}\"", escape_str(s)),
        JsxAttrValue::Expr(Expr::InlineAssign { name, value }) => {
            format!("move |_| {}", mutation_expr(name, value, declared))
        }
        JsxAttrValue::Expr(expr) if is_event => {
            format!("move |_| {}", expr_to_rust(expr, declared))
        }
        JsxAttrValue::Expr(expr) => format!("move || {}", expr_to_rust(expr, declared)),
    }
}

fn jsx_to_rust(node: &JsxNode, declared: &HashSet<String>, indent: usize) -> String {
    let mut out = String::new();
    match node {
        JsxNode::Text(s) => {
            push_line(&mut out, indent, &format!("\"{}\"", escape_str(s)));
        }
        JsxNode::VarInterp(name) => {
            push_line(
                &mut out,
                indent,
                &format!("{{move || {}}}", render_var_read(name, declared)),
            );
        }
        JsxNode::ExprInterp(expr) => {
            push_line(
                &mut out,
                indent,
                &format!("{{move || {}}}", expr_to_rust(expr, declared)),
            );
        }
        JsxNode::Element {
            tag,
            attrs,
            children,
            self_closing,
        } => {
            let attrs_str: String = attrs
                .iter()
                .map(|(name, value)| {
                    let (leptos_name, is_event) = jsx_attr_leptos_name(name);
                    format!(
                        " {}={}",
                        leptos_name,
                        jsx_attr_value(value, is_event, declared)
                    )
                })
                .collect();

            if *self_closing {
                push_line(&mut out, indent, &format!("<{tag}{attrs_str}/>"));
            } else if children.is_empty() {
                push_line(&mut out, indent, &format!("<{tag}{attrs_str}></{tag}>"));
            } else {
                push_line(&mut out, indent, &format!("<{tag}{attrs_str}>"));
                for child in children {
                    out.push_str(&jsx_to_rust(child, declared, indent + 1));
                }
                push_line(&mut out, indent, &format!("</{tag}>"));
            }
        }
    }
    out
}
