// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn About() -> impl IntoView {
    view! {
        <div>
            <h1>
                "About"
            </h1>
            <p>
                "This page is compiled from About.kitty and reached through leptos_router, exactly like example-app's CSR-only version — routing needs no SSR-specific changes at all."
            </p>
        </div>
    }
}

