// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;

#[path = "./Home.rs"]
mod __kittine_mod_home;
use __kittine_mod_home::{Home};
#[path = "./About.rs"]
mod __kittine_mod_about;
use __kittine_mod_about::{About};

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <nav>
                <A href="/".to_string()>
                    "Home"
                </A>
                <A href="/about".to_string()>
                    "About"
                </A>
            </nav>
            <main>
                <Routes fallback=About>
                    <Route path=StaticSegment("") view=Home/>
                    <Route path=StaticSegment("about") view=About/>
                </Routes>
            </main>
        </Router>
    }
}

