// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn Home() -> impl IntoView {
    let (count, set_count) = signal(0f64);
    view! {
        <div>
            <h1>
                "Kittine + SSR"
            </h1>
            <p>
                "This page is rendered server-side by cargo-leptos on first load, then hydrated client-side for interactivity — view-source shows the real content immediately, no JavaScript required."
            </p>
            <button on:click=move |_| set_count.update(|n| *n += 1f64)>
                "Clicks: "
                {move || count.get()}
            </button>
        </div>
    }
}

