// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn About() -> impl IntoView {
    view! {
        <div>
            <h1>
                "About"
            </h1>
            <p>
                "This page is compiled from About.kitty and reached entirely through leptos_router — Kittine has no routing syntax of its own, Router/Routes/Route/A are just ordinary components."
            </p>
        </div>
    }
}

