// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables)]

use leptos::prelude::*;

#[component]
pub fn App() -> impl IntoView {
    let (count, set_count) = signal(0);
    let (username, set_username) = signal("Admin");
    if username.get() == "Admin" {
        leptos::logging::log!("Welcome Admin");
    } else if username.get() == "User" {
        leptos::logging::log!("Welcome User");
    } else {
        leptos::logging::log!("no output");
    }
    view! {
        <div>
            <button on:click=move |_| set_count.update(|n| *n += 1)>
                "Clicks: "
                {move || count.get()}
            </button>
        </div>
    }
}

