// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code)]

use leptos::prelude::*;

#[path = "./Nav.rs"]
mod __kittine_mod_nav;
use __kittine_mod_nav::{Nav};

pub fn doubled(n: f64) -> f64 {
    n * 2f64
}

#[component]
pub fn App() -> impl IntoView {
    let (count, set_count) = signal(0f64);
    let (username, set_username) = signal("Admin");
    let (ready, set_ready) = signal(true);
    if username.get() == "Admin" {
        leptos::logging::log!("Welcome Admin");
    } else if username.get() == "User" {
        leptos::logging::log!("Welcome User");
    } else {
        leptos::logging::log!("no output");
    }
    for n in (vec![1, 2, 3]).into_iter() {
        leptos::logging::log!("{}", n);
    }
    view! {
        <div>
            <Nav active="Counter".to_string()/>
            <button on:click=move |_| set_count.update(|n| *n += 1f64)>
                "Clicks: "
                {move || count.get()}
                " (doubled: "
                {move || doubled(count.get())}
                ")"
            </button>
        </div>
    }
}

