// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;

#[path = "./Home.rs"]
mod __kittine_mod_home;
use __kittine_mod_home::{Home};
#[path = "./About.rs"]
mod __kittine_mod_about;
use __kittine_mod_about::{About};
#[path = "./User.rs"]
mod __kittine_mod_user;
use __kittine_mod_user::{User};
#[path = "./NotFound.rs"]
mod __kittine_mod_notfound;
use __kittine_mod_notfound::{NotFound};

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <nav>
                <A href="/".to_string()>
                    "Home"
                </A>
                <A href="/about".to_string()>
                    "About"
                </A>
                <A href="/user/42".to_string()>
                    "User 42"
                </A>
            </nav>
            <main>
                <Routes fallback=NotFound>
                    <Route path=StaticSegment("") view=Home/>
                    <Route path=StaticSegment("about") view=About/>
                    <Route path=(StaticSegment("user"), ParamSegment("id")) view=User/>
                </Routes>
            </main>
        </Router>
    }
}

