// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code)]

use leptos::prelude::*;

#[component]
pub fn Card(title: String, children: Children) -> impl IntoView {
    view! {
        <div class="card">
            <h3>
                {move || title.clone()}
            </h3>
            {children()}
        </div>
    }
}

