// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports, unused_parens)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn Card(title: String, children: Children) -> impl IntoView {
    view! {
        <div class="card">
            <h3>
                {{ let title = title.clone(); move || title.clone() }}
            </h3>
            {children()}
        </div>
    }
}

