// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports, unused_parens)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[path = "./components.rs"]
mod __kittine_mod_components;
use __kittine_mod_components::{Nav, Card, NavList};
#[path = "./Greetings.rs"]
mod __kittine_mod_greetings;
use __kittine_mod_greetings::{greet};
#[path = "./Shapes.rs"]
mod __kittine_mod_shapes;
use __kittine_mod_shapes::{Shapes};

fn doubled(n: f64) -> f64 {
    n * 2f64
}

pub fn isAdult(age: f64) -> bool {
    age >= 18f64
}

pub fn isWorkingAge(age: f64) -> bool {
    (age >= 18f64) && (age <= 65f64)
}

#[component]
pub fn Home() -> impl IntoView {
    let (count, set_count) = signal(0f64);
    let (username, set_username) = signal("Admin".to_string());
    let (ready, set_ready) = signal(true);
    let (age, set_age) = signal(25f64);
    let (sections, set_sections) = signal(vec!["Home".to_string(), "About".to_string(), "Contact".to_string()]);
    let (prices, set_prices) = signal(std::collections::HashMap::from([("milk".to_string(), 2f64), ("eggs".to_string(), 3f64), ("bread".to_string(), 4f64)]));
    leptos::logging::log!("{}", prices.get().get("milk").cloned().unwrap_or_default());
    leptos::logging::log!("{:?}", std::collections::HashMap::from([("a".to_string(), 1f64), ("b".to_string(), 2f64)]));
    let (revenue, set_revenue) = signal(1234567.891);
    leptos::logging::log!("{}", format!("{:.*}", (2) as usize, (revenue.get())));
    leptos::logging::log!("{}", { let __kittine_v = format!("{}", (revenue.get())); let (__kittine_sign, __kittine_digits): (&str, &str) = match __kittine_v.strip_prefix('-') { Some(rest) => ("-", rest), None => ("", __kittine_v.as_str()) }; let (__kittine_int, __kittine_frac): (&str, String) = match __kittine_digits.split_once('.') { Some((i, f)) => (i, format!(".{f}")), None => (__kittine_digits, String::new()) }; let __kittine_grouped: String = __kittine_int.as_bytes().rchunks(3).rev().map(|c| std::str::from_utf8(c).unwrap()).collect::<Vec<_>>().join(","); format!("{__kittine_sign}{__kittine_grouped}{__kittine_frac}") });
    leptos::logging::log!("{}", format!("{:0>1$}", (count.get()), (4) as usize));
    let (joined, set_joined) = signal(chrono::Utc::now());
    leptos::logging::log!("{}", (joined.get()).format(&("%Y-%m-%d")).to_string());
    let (launchDay, set_launchDay) = signal(chrono::NaiveDateTime::parse_from_str(&("2026-01-01 09:00:00"), &("%Y-%m-%d %H:%M:%S")).unwrap().and_utc());
    leptos::logging::log!("{}", (launchDay.get()).format(&("%B %d, %Y")).to_string());
    let (signupEmail, set_signupEmail) = signal("admin@example.com".to_string());
    let (signupWebsite, set_signupWebsite) = signal("https://kittine.dev".to_string());
    let (signupZip, set_signupZip) = signal("90210".to_string());
    leptos::logging::log!("{}", { let __kittine_owned = (signupEmail.get()); let __kittine_v: &str = __kittine_owned.as_ref(); match __kittine_v.split_once('@') { Some((__kittine_local, __kittine_domain)) => !__kittine_local.is_empty() && !__kittine_domain.is_empty() && __kittine_domain.contains('.') && !__kittine_domain.starts_with('.') && !__kittine_domain.ends_with('.') && !__kittine_v.contains(' '), None => false, } });
    leptos::logging::log!("{}", { let __kittine_owned = (signupWebsite.get()); let __kittine_v: &str = __kittine_owned.as_ref(); let __kittine_rest = __kittine_v.strip_prefix("https://").or_else(|| __kittine_v.strip_prefix("http://")); match __kittine_rest { Some(__kittine_after_scheme) => { let __kittine_host = __kittine_after_scheme.split('/').next().unwrap_or(""); !__kittine_host.is_empty() && __kittine_host.contains('.') && !__kittine_v.contains(' ') }, None => false, } });
    leptos::logging::log!("{}", (signupZip.get()).trim().parse::<f64>().is_ok());
    leptos::logging::log!("{}", { let __kittine_owned = (username.get()); let __kittine_v: &str = __kittine_owned.as_ref(); !__kittine_v.is_empty() && __kittine_v.chars().all(|c| c.is_alphabetic()) });
    leptos::logging::log!("{}", (((username.get()).chars().count() as f64) >= ((3) as f64) && ((username.get()).chars().count() as f64) <= ((20) as f64)));
    leptos::logging::warn!("demonstrating warn< -- a real leptos::logging::warn! call");
    leptos::logging::error!("demonstrating error< -- a real leptos::logging::error! call");
    if username.get() == "Admin" {
        leptos::logging::log!("Welcome Admin");
    } else if username.get() == "User" {
        leptos::logging::log!("Welcome User");
    } else {
        leptos::logging::log!("no output");
    }
    if age.get() >= 18f64 {
        leptos::logging::log!("adult");
    } else if age.get() < 13f64 {
        leptos::logging::log!("child");
    } else {
        leptos::logging::log!("teen");
    }
    if (age.get() >= 18f64) && (ready.get() == true) {
        leptos::logging::log!("ready adult");
    } else if (age.get() < 13f64) || (age.get() >= 65f64) {
        leptos::logging::log!("discount age");
    }
    leptos::logging::log!("{}", isAdult(age.get()));
    leptos::logging::log!("{}", isWorkingAge(age.get()));
    leptos::logging::log!("{}", greet("World".to_string()));
    for n in (vec![1, 2, 3]).into_iter() {
        leptos::logging::log!("{}", n);
    }
    view! {
        <div>
            <Nav active="Counter".to_string()/>
            <button on:click=move |_| set_count.update(|n| *n += 1f64)>
                "Clicks: "
                {move || count.get()}
                " (doubled: "
                {move || doubled(count.get())}
                ")"
            </button>
            <p>
                "Username: "
                {move || username.get()}
                <button on:click=move |_| set_username.update(|n| *n = "Guest".to_string())>
                    "Reset to Guest"
                </button>
                <input placeholder="Type a username" on:input=move |ev| set_username.update(|n| *n = event_target_value(&ev))/>
            </p>
            <ul>
                <For each=move || vec![1, 2, 3] key=|n| format!("{n:?}") let:n>
                    <li>
                        {{ let n = n.clone(); move || n.clone() }}
                    </li>
                </For>
            </ul>
            <Card title="About this page".to_string()>
                <p>
                    "This card's children came from the composing view."
                </p>
            </Card>
            <NavList items=sections.get()/>
            <p>
                "Milk costs: "
                {move || prices.get().get("milk").cloned().unwrap_or_default()}
            </p>
            <p>
                "Revenue: $"
                {move || format!("{:.*}", (2) as usize, (revenue.get()))}
                " ("
                {move || { let __kittine_v = format!("{}", (revenue.get())); let (__kittine_sign, __kittine_digits): (&str, &str) = match __kittine_v.strip_prefix('-') { Some(rest) => ("-", rest), None => ("", __kittine_v.as_str()) }; let (__kittine_int, __kittine_frac): (&str, String) = match __kittine_digits.split_once('.') { Some((i, f)) => (i, format!(".{f}")), None => (__kittine_digits, String::new()) }; let __kittine_grouped: String = __kittine_int.as_bytes().rchunks(3).rev().map(|c| std::str::from_utf8(c).unwrap()).collect::<Vec<_>>().join(","); format!("{__kittine_sign}{__kittine_grouped}{__kittine_frac}") }}
                ") / order #"
                {move || format!("{:0>1$}", (count.get()), (4) as usize)}
            </p>
            <p>
                "Joined: "
                {move || (joined.get()).format(&("%Y-%m-%d")).to_string()}
                " / Launch day: "
                {move || (launchDay.get()).format(&("%B %d, %Y")).to_string()}
            </p>
            <p>
                "Signup email: "
                <input placeholder="you@example.com" on:input=move |ev| set_signupEmail.update(|n| *n = event_target_value(&ev))/>
                {move || signupEmail.get()}
                " (valid: "
                {move || { let __kittine_owned = (signupEmail.get()); let __kittine_v: &str = __kittine_owned.as_ref(); match __kittine_v.split_once('@') { Some((__kittine_local, __kittine_domain)) => !__kittine_local.is_empty() && !__kittine_domain.is_empty() && __kittine_domain.contains('.') && !__kittine_domain.starts_with('.') && !__kittine_domain.ends_with('.') && !__kittine_v.contains(' '), None => false, } }}
                ")"
            </p>
            <p>
                "Website valid: "
                {move || { let __kittine_owned = (signupWebsite.get()); let __kittine_v: &str = __kittine_owned.as_ref(); let __kittine_rest = __kittine_v.strip_prefix("https://").or_else(|| __kittine_v.strip_prefix("http://")); match __kittine_rest { Some(__kittine_after_scheme) => { let __kittine_host = __kittine_after_scheme.split('/').next().unwrap_or(""); !__kittine_host.is_empty() && __kittine_host.contains('.') && !__kittine_v.contains(' ') }, None => false, } }}
                " / Zip is numeric: "
                {move || (signupZip.get()).trim().parse::<f64>().is_ok()}
                " / Username is alphabetic: "
                {move || { let __kittine_owned = (username.get()); let __kittine_v: &str = __kittine_owned.as_ref(); !__kittine_v.is_empty() && __kittine_v.chars().all(|c| c.is_alphabetic()) }}
                " / Username length 3-20: "
                {move || (((username.get()).chars().count() as f64) >= ((3) as f64) && ((username.get()).chars().count() as f64) <= ((20) as f64))}
            </p>
            <Shapes/>
        </div>
    }
}

