// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;

#[path = "./Nav.rs"]
mod __kittine_mod_nav;
use __kittine_mod_nav::{Nav};
#[path = "./Card.rs"]
mod __kittine_mod_card;
use __kittine_mod_card::{Card};
#[path = "./NavList.rs"]
mod __kittine_mod_navlist;
use __kittine_mod_navlist::{NavList};

fn doubled(n: f64) -> f64 {
    n * 2f64
}

pub fn isAdult(age: f64) -> bool {
    age >= 18f64
}

pub fn isWorkingAge(age: f64) -> bool {
    (age >= 18f64) && (age <= 65f64)
}

#[component]
pub fn Home() -> impl IntoView {
    let (count, set_count) = signal(0f64);
    let (username, set_username) = signal("Admin".to_string());
    let (ready, set_ready) = signal(true);
    let (age, set_age) = signal(25f64);
    let (sections, set_sections) = signal(vec!["Home".to_string(), "About".to_string(), "Contact".to_string()]);
    if username.get() == "Admin" {
        leptos::logging::log!("Welcome Admin");
    } else if username.get() == "User" {
        leptos::logging::log!("Welcome User");
    } else {
        leptos::logging::log!("no output");
    }
    if age.get() >= 18f64 {
        leptos::logging::log!("adult");
    } else if age.get() < 13f64 {
        leptos::logging::log!("child");
    } else {
        leptos::logging::log!("teen");
    }
    if (age.get() >= 18f64) && (ready.get() == true) {
        leptos::logging::log!("ready adult");
    } else if (age.get() < 13f64) || (age.get() >= 65f64) {
        leptos::logging::log!("discount age");
    }
    leptos::logging::log!("{}", isAdult(age.get()));
    leptos::logging::log!("{}", isWorkingAge(age.get()));
    for n in (vec![1, 2, 3]).into_iter() {
        leptos::logging::log!("{}", n);
    }
    view! {
        <div>
            <Nav active="Counter".to_string()/>
            <button on:click=move |_| set_count.update(|n| *n += 1f64)>
                "Clicks: "
                {move || count.get()}
                " (doubled: "
                {move || doubled(count.get())}
                ")"
            </button>
            <ul>
                <For each=move || vec![1, 2, 3] key=|n| format!("{n}") let:n>
                    <li>
                        {move || n.clone()}
                    </li>
                </For>
            </ul>
            <Card title="About this page".to_string()>
                <p>
                    "This card's children came from the composing view."
                </p>
            </Card>
            <NavList items=sections.get()/>
        </div>
    }
}

