// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;

#[component]
pub fn Nav(active: String) -> impl IntoView {
    view! {
        <nav>
            "Section: "
            {{ let active = active.clone(); move || active.clone() }}
        </nav>
    }
}

