// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code)]

use leptos::prelude::*;

#[component]
pub fn Nav(active: String) -> impl IntoView {
    view! {
        <nav>
            "Section: "
            {move || active.clone()}
        </nav>
    }
}

