// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports, unused_parens)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn NavList(items: Vec<String>) -> impl IntoView {
    view! {
        <ul>
            <For each=move || items.clone() key=|item| item.clone().to_uppercase() let:item>
                <li>
                    {{ let item = item.clone(); move || item.clone() }}
                </li>
            </For>
        </ul>
    }
}

