// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;

#[component]
pub fn NavList(items: Vec<String>) -> impl IntoView {
    view! {
        <ul>
            <For each=move || items.clone() key=|item| item.clone().to_uppercase() let:item>
                <li>
                    {move || item.clone()}
                </li>
            </For>
        </ul>
    }
}

