// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;

#[component]
pub fn NotFound() -> impl IntoView {
    view! {
        <div>
            <h1>
                "404"
            </h1>
            <p>
                "That page doesn't exist."
            </p>
        </div>
    }
}

