// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[derive(Clone, Debug)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[derive(Clone, Debug)]
pub struct Holder<T> {
    pub value: T,
}

#[derive(Clone, Debug)]
pub enum Shape {
    Circle(f64),
    Square(f64),
    Idle,
}

#[component]
pub fn Shapes() -> impl IntoView {
    let (origin, set_origin) = signal(Point { x: 3f64, y: 4f64 });
    let (shape, set_shape) = signal(Shape::Circle(5f64));
    let (description, set_description) = signal("unknown".to_string());
    let (numHolder, set_numHolder) = signal(Holder { value: 42f64 });
    let (wordHolder, set_wordHolder) = signal(Holder { value: "hello".to_string() });
    match shape.get() {
        Shape::Circle(r) => {
            set_description.update(|n| *n = "circle".to_string());
        }
        Shape::Square(s) => {
            set_description.update(|n| *n = "square".to_string());
        }
        _ => {
            set_description.update(|n| *n = "idle".to_string());
        }
    }
    view! {
        <div>
            <p>
                "Origin x: "
                {move || origin.get().x}
            </p>
            <p>
                "Origin y: "
                {move || origin.get().y}
            </p>
            <p>
                "Shape: "
                {move || description.get()}
            </p>
            <p>
                "NumHolder: "
                {move || numHolder.get().value}
            </p>
            <p>
                "WordHolder: "
                {move || wordHolder.get().value}
            </p>
        </div>
    }
}

