// Generated by kittine-compiler. Do not edit by hand.
#![allow(unused_braces, unused_variables, dead_code, unused_imports)]

use leptos::prelude::*;
use leptos_router::components::*;
use leptos_router::*;
use leptos_router::hooks::*;
use leptos_meta::*;

#[component]
pub fn User() -> impl IntoView {
    let navigate = use_navigate();
    view! {
        <div>
            <h1>
                "User"
            </h1>
            <p>
                "This page's route ('/user/:id') is a dynamic segment — reached via a tuple path {(StaticSegment('user'), ParamSegment('id'))}, with the id read back out via use_params_map(), a plain leptos_router hook call."
            </p>
            <p>
                "User id: "
                {move || use_params_map().get().get("id").unwrap_or_default()}
            </p>
            <button on:click={ let navigate = navigate.clone(); move |_| navigate.clone()("/", NavigateOptions::default()) }>
                "Go home (programmatic navigation)"
            </button>
            <button on:click={ let navigate = navigate.clone(); move |_| navigate.clone()("/about", NavigateOptions::default()) }>
                "Go to About (same held navigate, called from a second button)"
            </button>
        </div>
    }
}

